-- Remove SR (Structured Report) records from cd_print_log.
-- SR studies are auto-generated by PACS and are not real patient studies.

DELETE FROM cd_print_log
WHERE COALESCE(study_modality, '') = 'SR';
