-- Migration 0103: make the ORU diagnosis phrase->label vocabulary DB-configurable.
--
-- routes/oru_analytics.py's DIAGNOSES list (phrase -> canonical label, used for the
-- word cloud and critical findings log) and nlp_worker/worker.py's duplicate copy of
-- it were both hardcoded Python constants -- any addition/edit needed a code change
-- and redeploy of both files. Seeded below with the current 106 unique phrases.

CREATE TABLE IF NOT EXISTS oru_diagnosis_vocabulary (
    id              SERIAL PRIMARY KEY,
    phrase          TEXT NOT NULL UNIQUE,
    canonical_label TEXT NOT NULL,
    is_benign       BOOLEAN NOT NULL DEFAULT FALSE,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_oru_diag_vocab_active ON oru_diagnosis_vocabulary (active);

INSERT INTO oru_diagnosis_vocabulary (phrase, canonical_label, is_benign) VALUES
  ('pneumothorax', 'Pneumothorax', FALSE),
  ('pulmonary embolism', 'Pulmonary Embolism', FALSE),
  ('pleural effusion', 'Pleural Effusion', FALSE),
  ('épanchement pleural', 'Pleural Effusion', FALSE),
  ('consolidation', 'Consolidation', FALSE),
  ('pneumonia', 'Pneumonia', FALSE),
  ('pneumonie', 'Pneumonia', FALSE),
  ('atelectasis', 'Atelectasis', FALSE),
  ('atélectasie', 'Atelectasis', FALSE),
  ('emphysema', 'Emphysema', FALSE),
  ('pulmonary edema', 'Pulmonary Edema', FALSE),
  ('pulmonary oedema', 'Pulmonary Edema', FALSE),
  ('oedème pulmonaire', 'Pulmonary Edema', FALSE),
  ('hemothorax', 'Hemothorax', FALSE),
  ('haemothorax', 'Hemothorax', FALSE),
  ('cardiomegaly', 'Cardiomegaly', FALSE),
  ('pericardial effusion', 'Pericardial Effusion', FALSE),
  ('aortic dissection', 'Aortic Dissection', FALSE),
  ('aortic aneurysm', 'Aortic Aneurysm', FALSE),
  ('intracranial hemorrhage', 'Intracranial Hemorrhage', FALSE),
  ('intracranial haemorrhage', 'Intracranial Hemorrhage', FALSE),
  ('subdural hematoma', 'Subdural Hematoma', FALSE),
  ('subdural haematoma', 'Subdural Hematoma', FALSE),
  ('epidural hematoma', 'Epidural Hematoma', FALSE),
  ('subarachnoid hemorrhage', 'Subarachnoid Hemorrhage', FALSE),
  ('hemorrhage', 'Hemorrhage', FALSE),
  ('haemorrhage', 'Hemorrhage', FALSE),
  ('hematoma', 'Hematoma', FALSE),
  ('haematoma', 'Hematoma', FALSE),
  ('stroke', 'Stroke', FALSE),
  ('infarction', 'Infarction', FALSE),
  ('infarct', 'Infarction', FALSE),
  ('ischemia', 'Ischemia', FALSE),
  ('ischaemia', 'Ischemia', FALSE),
  ('aneurysm', 'Aneurysm', FALSE),
  ('hydrocephalus', 'Hydrocephalus', FALSE),
  ('midline shift', 'Midline Shift', FALSE),
  ('appendicitis', 'Appendicitis', FALSE),
  ('cholecystitis', 'Cholecystitis', FALSE),
  ('cholelithiasis', 'Cholelithiasis', FALSE),
  ('gallstone', 'Gallstone', FALSE),
  ('bowel obstruction', 'Bowel Obstruction', FALSE),
  ('obstruction', 'Obstruction', FALSE),
  ('perforation', 'Perforation', FALSE),
  ('abscess', 'Abscess', FALSE),
  ('hepatomegaly', 'Hepatomegaly', FALSE),
  ('splenomegaly', 'Splenomegaly', FALSE),
  ('ascites', 'Ascites', FALSE),
  ('pancreatitis', 'Pancreatitis', FALSE),
  ('diverticulitis', 'Diverticulitis', FALSE),
  ('hernia', 'Hernia', FALSE),
  ('deep vein thrombosis', 'DVT', FALSE),
  ('dvt', 'DVT', FALSE),
  ('thrombosis', 'Thrombosis', FALSE),
  ('thrombose', 'Thrombosis', FALSE),
  ('occlusion', 'Occlusion', FALSE),
  ('stenosis', 'Stenosis', FALSE),
  ('sténose', 'Stenosis', FALSE),
  ('dissection', 'Dissection', FALSE),
  ('embolism', 'Embolism', FALSE),
  ('embolus', 'Embolism', FALSE),
  ('fracture', 'Fracture', FALSE),
  ('dislocation', 'Dislocation', FALSE),
  ('luxation', 'Dislocation', FALSE),
  ('osteoporosis', 'Osteoporosis', FALSE),
  ('arthritis', 'Arthritis', FALSE),
  ('arthrose', 'Arthritis', FALSE),
  ('osteomyelitis', 'Osteomyelitis', FALSE),
  ('spondylosis', 'Spondylosis', FALSE),
  ('disc herniation', 'Disc Herniation', FALSE),
  ('disk herniation', 'Disc Herniation', FALSE),
  ('herniated disc', 'Disc Herniation', FALSE),
  ('spinal stenosis', 'Spinal Stenosis', FALSE),
  ('metastasis', 'Metastasis', FALSE),
  ('metastases', 'Metastasis', FALSE),
  ('métastase', 'Metastasis', FALSE),
  ('malignancy', 'Malignancy', FALSE),
  ('malignant', 'Malignancy', FALSE),
  ('carcinoma', 'Carcinoma', FALSE),
  ('carcinome', 'Carcinoma', FALSE),
  ('lymphoma', 'Lymphoma', FALSE),
  ('lymphome', 'Lymphoma', FALSE),
  ('adenoma', 'Adenoma', FALSE),
  ('adénome', 'Adenoma', FALSE),
  ('neoplasm', 'Neoplasm', FALSE),
  ('tumor', 'Tumor / Mass', FALSE),
  ('tumour', 'Tumor / Mass', FALSE),
  ('tumeur', 'Tumor / Mass', FALSE),
  ('mass', 'Tumor / Mass', FALSE),
  ('nodule', 'Nodule', FALSE),
  ('lesion', 'Lesion', FALSE),
  ('lésion', 'Lesion', FALSE),
  ('cyst', 'Cyst', FALSE),
  ('kyste', 'Cyst', FALSE),
  ('hydronephrosis', 'Hydronephrosis', FALSE),
  ('nephrolithiasis', 'Nephrolithiasis', FALSE),
  ('urolithiasis', 'Nephrolithiasis', FALSE),
  ('renal calculus', 'Renal Calculus', FALSE),
  ('kidney stone', 'Renal Calculus', FALSE),
  ('empyema', 'Empyema', FALSE),
  ('cellulitis', 'Cellulitis', FALSE),
  ('no acute', 'No Acute Finding', TRUE),
  ('unremarkable', 'Unremarkable', TRUE),
  ('within normal limits', 'Normal', TRUE),
  ('sans particularité', 'Normal', TRUE),
  ('normal study', 'Normal', TRUE)
ON CONFLICT (phrase) DO NOTHING;
