import os
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_login import login_user, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import text
from db import User, UserPagePermission, db

auth_bp = Blueprint('auth', __name__)

def _get_demo_settings():
    """Returns (demo_mode: bool, demo_user: str)."""
    try:
        rows = db.session.execute(text(
            "SELECT key, value FROM settings WHERE key IN ('demo_mode','demo_user')"
        )).fetchall()
        d = {r[0]: r[1] for r in rows}
        return d.get('demo_mode', 'false').lower() == 'true', d.get('demo_user', '')
    except Exception:
        return False, ''


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    demo_mode, _ = _get_demo_settings()
    if demo_mode:
        flash('Registration is disabled during demo mode.', 'warning')
        return redirect(url_for('auth.login'))

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        role = request.form.get('role')
        admin_key_input = request.form.get('admin_key')

        # 1. Validation: Check if username exists
        if User.query.filter_by(username=username).first():
            flash('Username already taken.', 'danger')
            return redirect(url_for('auth.register'))

        # 2. Validation: Admin Protection
        if role == 'admin':
            master_key = os.environ.get('MASTER_ADMIN_KEY', '')
            if not master_key:
                flash('Admin registration is not configured.', 'danger')
                return redirect(url_for('auth.register'))
            if admin_key_input != master_key:
                flash('Incorrect Admin Secret Key.', 'danger')
                return redirect(url_for('auth.register'))

        try:
            # STEP 1: Insert the new user
            new_user = User(
                username=username,
                password_hash=generate_password_hash(password, method='pbkdf2:sha256'),
                role=role
            )
            db.session.add(new_user)

            # STEP 2: Flush to get the ID generated by Postgres
            db.session.flush()

            if role == 'viewer':
                # Grant access to all base reports
                db.session.execute(text("""
                    INSERT INTO report_access_control (user_id, is_enabled, report_template_id)
                    SELECT :uid, true, unnest(ARRAY[22, 23, 25, 27, 29])
                """), {'uid': new_user.id})
                # Grant page access by default for viewers
                db.session.add(UserPagePermission(user_id=new_user.id, page_key='report_ai', is_enabled=True))
                db.session.add(UserPagePermission(user_id=new_user.id, page_key='oru', is_enabled=True))

            elif role == 'tec':
                # Tec users only get HL7 Orders page access
                db.session.add(UserPagePermission(user_id=new_user.id, page_key='hl7_orders', is_enabled=True))

            db.session.commit()

            flash('Registration successful!', 'success')
            return redirect(url_for('auth.login'))

        except Exception as e:
            db.session.rollback()
            # This will show up in your 'docker logs rayd_app_container'
            print(f"CRITICAL REGISTRATION ERROR: {str(e)}")
            flash('A database error occurred. Please try again.', 'danger')

    return render_template('register.html')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        dest = 'admin.admin_dashboard' if current_user.role == 'admin' else 'viewer.viewer_dashboard'
        return redirect(url_for(dest))

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        
        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password_hash, password):
            # Demo mode: only admin and the designated demo user may log in
            demo_mode, demo_user = _get_demo_settings()
            if demo_mode and user.role != 'admin' and user.username != demo_user:
                flash('Access is restricted during demo mode.', 'warning')
                return redirect(url_for('auth.login'))

            login_user(user)
            session.permanent = True
            flash('Login successful!', 'success')

            if user.role == 'tec':
                dest = url_for('hl7_orders.hl7_orders_page')
            else:
                dest = url_for('viewer.viewer_dashboard')
            return redirect(dest)

        flash('Invalid username or password.', 'danger')

    return render_template('login.html')

@auth_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('auth.login'))
