import os
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_login import login_user, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import text
from db import User, db

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        role = request.form.get('role')
        admin_key_input = request.form.get('admin_key')

        # 1. Validation: Check if username exists
        if User.query.filter_by(username=username).first():
            flash('Username already taken.', 'danger')
            return redirect(url_for('auth.register'))

        # 2. Validation: Admin Protection
        if role == 'admin':
            master_key = os.environ.get('MASTER_ADMIN_KEY', 'SuperSecret123')
            if admin_key_input != master_key:
                flash('Incorrect Admin Secret Key.', 'danger')
                return redirect(url_for('auth.register'))

        try:
            # STEP 1: Insert the new user
            new_user = User(
                username=username,
                password_hash=generate_password_hash(password, method='pbkdf2:sha256'),
                role=role
            )
            db.session.add(new_user)
            
            # STEP 2: Flush to get the specific ID generated by Postgres
            db.session.flush() 

            # STEP 3: Use that specific ID in your exact SQL query
            sql = text("""
                INSERT INTO report_access_control (user_id, is_enabled, report_template_id)
                SELECT :uid, true, unnest(ARRAY[22, 23, 25, 27, 29])
            """)
            
            db.session.execute(sql, {'uid': new_user.id})

            # Commit both steps as one single transaction
            db.session.commit()
            
            flash('Registration successful! Access to reports 22, 23, 25, 27, and 29 has been granted.', 'success')
            return redirect(url_for('auth.login'))

        except Exception as e:
            db.session.rollback()
            # This will show up in your 'docker logs rayd_app_container'
            print(f"CRITICAL REGISTRATION ERROR: {str(e)}")
            flash('A database error occurred. Please try again.', 'danger')

    return render_template('register.html')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        dest = 'admin.admin_dashboard' if current_user.role == 'admin' else 'viewer.viewer_dashboard'
        return redirect(url_for(dest))

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        
        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password_hash, password):
            login_user(user)
            session.permanent = True
            flash('Login successful!', 'success')
            
            dest = 'admin.admin_dashboard' if user.role == 'admin' else 'viewer.viewer_dashboard'
            return redirect(url_for(dest))
        
        flash('Invalid username or password.', 'danger')

    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('auth.login'))
